# Workflow that publishes a new TACO version once a matching tag is created
name: Publish to crates.io, Create Release Draft & Build Container Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-alpha.*"
      - "v*.*.*-beta.*"
      - "v*.*.*-rc.*"

env:
  CARGO_TERM_COLOR: always
  MIN_RUST_VERSION: "1.92.0"
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  # Validate minimum supported Rust version declared in `Cargo.toml`.
  # Note that warnings are allowed as some may appear due to backwards
  # compatiblity issues.
  minimum-supported:
    name: Minimum version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust version
        run: rustup install ${MIN_RUST_VERSION}
      - name: Install Dependencies (Z3,CVC5,Graphviz)
        run: sudo apt-get install -y z3 cvc5 graphviz
      - name: check
        run: cargo +${MIN_RUST_VERSION} check --all-features
      - name: check
        run: cargo +${MIN_RUST_VERSION} test --all-features

  # Publish the new version to crates.io
  crates_io_publish:
    name: Publish (Crates.io) & Create Release Draft
    needs: minimum-supported
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC token exchange
      contents: write # required to create a release
    steps:
      - uses: actions/checkout@v4
      - name: Install rust version
        run: rustup install ${MIN_RUST_VERSION}
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo publish --workspace
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          draft: true
          body: "This is a release draft generated by Github Actions..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build the TACO container for the release
  build_container:
    name: Build Container Image
    environment: release
    needs: minimum-supported
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        id: push
        with:
          platforms: linux/amd64 # ,linux/arm64 (currently fails for CUDD)
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
